// ============================================================
// FSGT94 Volleyball Championship - Data File
// Extracted from index.html
// ============================================================

// 1. TEAMS
const TEAMS = {
  jen: { name: 'Jen et ses Saints', short: 'JS', logo: 'logo-jen', color: '#9b59b6' },
  kiki: { name: 'Kiki Team', short: 'KT', logo: 'logo-kiki', color: '#3498db' },
  rhsp: { name: 'Red Hot Sucy Pépère', short: 'RH', logo: 'logo-rhsp', color: '#e74c3c' },
  resc: { name: 'Les Rescapés', short: 'LR', logo: 'logo-resc', color: '#2ecc71' },
  marv: { name: 'Marvels 4', short: 'M4', logo: 'logo-marv', color: '#f39c12' },
  rsc: { name: 'RSC Champigny 1', short: 'RC', logo: 'logo-rsc', color: '#1abc9c' },
  manu: { name: 'Manu Andy-sport', short: 'MA', logo: 'logo-manu', color: '#e67e22' },
  bier: { name: 'Bières et le loup', short: 'BL', logo: 'logo-bier', color: '#f1c40f' },
  rhin: { name: 'Rhinos Féroces', short: 'RF', logo: 'logo-rhin', color: '#95a5a6' },
  star: { name: 'StarPAFF', short: 'SP', logo: 'logo-star', color: '#34495e' }
};

// 2. STANDINGS
const STANDINGS = [
  { rank: 1, team: 'jen', mj: 10, g: 10, p: 0, setPlus: 30, setMinus: 3, ds: 27, coefSet: '10.00', ptsPlus: 817, ptsMinus: 614, dp: '+203', coefPts: '1.33', pts: 20, form: ['W','W','W','W','W','W','W','W','W','W'] },
  { rank: 2, team: 'kiki', mj: 9, g: 7, p: 2, setPlus: 22, setMinus: 13, ds: 9, coefSet: '1.69', ptsPlus: 804, ptsMinus: 711, dp: '+93', coefPts: '1.13', pts: 16, form: ['W','W','L','W','W','W','W','L','W'] },
  { rank: 3, team: 'resc', mj: 8, g: 5, p: 3, setPlus: 20, setMinus: 13, ds: 7, coefSet: '1.54', ptsPlus: 743, ptsMinus: 706, dp: '+37', coefPts: '1.05', pts: 13, form: ['W','W','W','L','L','W','L','W'] },
  { rank: 4, team: 'rhsp', mj: 10, g: 6, p: 4, setPlus: 20, setMinus: 17, ds: 3, coefSet: '1.18', ptsPlus: 796, ptsMinus: 765, dp: '+31', coefPts: '1.04', pts: 16, form: ['L','W','W','W','W','W','L','W','L','L'] },
  { rank: 5, team: 'marv', mj: 10, g: 6, p: 4, setPlus: 22, setMinus: 20, ds: 2, coefSet: '1.10', ptsPlus: 904, ptsMinus: 902, dp: '+2', coefPts: '1.00', pts: 16, form: ['W','W','L','W','W','L','W','L','W','L'] },
  { rank: 6, team: 'bier', mj: 10, g: 5, p: 5, setPlus: 18, setMinus: 19, ds: -1, coefSet: '0.95', ptsPlus: 838, ptsMinus: 808, dp: '+30', coefPts: '1.04', pts: 15, form: ['W','L','L','L','W','L','L','W','W','W'] },
  { rank: 7, team: 'rsc', mj: 8, g: 3, p: 5, setPlus: 15, setMinus: 19, ds: -4, coefSet: '0.79', ptsPlus: 699, ptsMinus: 715, dp: '-16', coefPts: '0.98', pts: 11, form: ['L','W','L','L','W','L','L','W'] },
  { rank: 8, team: 'manu', mj: 8, g: 2, p: 6, setPlus: 10, setMinus: 18, ds: -8, coefSet: '0.56', ptsPlus: 595, ptsMinus: 645, dp: '-50', coefPts: '0.92', pts: 10, form: ['L','L','W','L','L','W','L','L'] },
  { rank: 9, team: 'rhin', mj: 9, g: 2, p: 7, setPlus: 14, setMinus: 21, ds: -7, coefSet: '0.67', ptsPlus: 744, ptsMinus: 793, dp: '-49', coefPts: '0.94', pts: 11, form: ['L','L','L','L','W','L','L','W','L'] },
  { rank: 10, team: 'star', mj: 10, g: 0, p: 10, setPlus: 2, setMinus: 30, ds: -28, coefSet: '0.07', ptsPlus: 513, ptsMinus: 794, dp: '-281', coefPts: '0.65', pts: 10, form: ['L','L','L','L','L','L','L','L','L','L'] },
];

// 3. MATCHES_PLAYED
const MATCHES_PLAYED = [
  { date: '12/02/2026', home: 'jen', away: 'rhsp', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '11/02/2026', home: 'star', away: 'kiki', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '11/02/2026', home: 'rsc', away: 'marv', scoreHome: 3, scoreAway: 2, homeWin: true, status: 'Terminé' },
  { date: '10/02/2026', home: 'bier', away: 'manu', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '09/02/2026', home: 'resc', away: 'rhin', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '29/01/2026', home: 'marv', away: 'rsc', scoreHome: 3, scoreAway: 2, homeWin: true, status: 'Terminé' },
  { date: '29/01/2026', home: 'jen', away: 'manu', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '27/01/2026', home: 'bier', away: 'star', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '26/01/2026', home: 'kiki', away: 'jen', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '26/01/2026', home: 'rhin', away: 'rhsp', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '22/01/2026', home: 'jen', away: 'resc', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '21/01/2026', home: 'manu', away: 'rhin', scoreHome: 3, scoreAway: 2, homeWin: true, status: 'Terminé' },
  { date: '21/01/2026', home: 'rsc', away: 'bier', scoreHome: 2, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '19/01/2026', home: 'rhsp', away: 'star', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '19/01/2026', home: 'kiki', away: 'marv', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '15/01/2026', home: 'marv', away: 'manu', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '14/01/2026', home: 'star', away: 'rsc', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '13/01/2026', home: 'bier', away: 'resc', scoreHome: 1, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '12/01/2026', home: 'rhsp', away: 'kiki', scoreHome: 2, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '12/01/2026', home: 'rhin', away: 'jen', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '08/01/2026', home: 'jen', away: 'marv', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '11/12/2025', home: 'marv', away: 'bier', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '11/12/2025', home: 'jen', away: 'rsc', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '08/12/2025', home: 'kiki', away: 'manu', scoreHome: 2, scoreAway: 2, homeWin: true, status: 'Kiki pts' },
  { date: '08/12/2025', home: 'resc', away: 'rhsp', scoreHome: 2, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '08/12/2025', home: 'star', away: 'rhin', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '03/12/2025', home: 'manu', away: 'star', scoreHome: 3, scoreAway: 0, homeWin: true, status: 'Terminé' },
  { date: '02/12/2025', home: 'marv', away: 'resc', scoreHome: 3, scoreAway: 2, homeWin: true, status: 'Terminé' },
  { date: '01/12/2025', home: 'rhsp', away: 'rsc', scoreHome: 3, scoreAway: 2, homeWin: true, status: 'Terminé' },
  { date: '01/12/2025', home: 'rhin', away: 'bier', scoreHome: 1, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '26/11/2025', home: 'star', away: 'jen', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '25/11/2025', home: 'bier', away: 'kiki', scoreHome: 1, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '24/11/2025', home: 'rhsp', away: 'marv', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '20/11/2025', home: 'jen', away: 'bier', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '19/11/2025', home: 'rsc', away: 'kiki', scoreHome: 2, scoreAway: 2, homeWin: true, status: 'RSC pts' },
  { date: '19/11/2025', home: 'manu', away: 'rhsp', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '19/11/2025', home: 'star', away: 'resc', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '17/11/2025', home: 'rhin', away: 'marv', scoreHome: 2, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '06/11/2025', home: 'marv', away: 'star', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '04/11/2025', home: 'bier', away: 'rhsp', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '03/11/2025', home: 'resc', away: 'rsc', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '03/11/2025', home: 'kiki', away: 'rhin', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' },
  { date: '15/10/2025', home: 'manu', away: 'bier', scoreHome: 1, scoreAway: 2, homeWin: false, status: 'Terminé' },
  { date: '13/10/2025', home: 'rhsp', away: 'jen', scoreHome: 0, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '13/10/2025', home: 'rhin', away: 'resc', scoreHome: 1, scoreAway: 3, homeWin: false, status: 'Terminé' },
  { date: '13/10/2025', home: 'kiki', away: 'star', scoreHome: 3, scoreAway: 1, homeWin: true, status: 'Terminé' }
];

// 4. MATCHES_UPCOMING
const MATCHES_UPCOMING = [
  { date: 'N/C', home: 'rsc', away: 'rhin', status: 'Reporté' },
  { date: '16/02/2026', home: 'star', away: 'marv', status: 'Sem. 11' },
  { date: '16/02/2026', home: 'rhsp', away: 'bier', status: 'Sem. 11' },
  { date: '16/02/2026', home: 'rhin', away: 'kiki', status: 'Sem. 11' },
  { date: '18/02/2026', home: 'manu', away: 'jen', status: 'Sem. 11' },
  { date: '18/02/2026', home: 'rsc', away: 'resc', status: 'Sem. 11' },
  { date: '02/03/2026', home: 'kiki', away: 'resc', status: 'Reporté' },
  { date: '09/03/2026', home: 'kiki', away: 'rsc', status: 'Sem. 12' },
  { date: '09/03/2026', home: 'rhsp', away: 'manu', status: 'Sem. 12' },
  { date: '09/03/2026', home: 'resc', away: 'star', status: 'Sem. 12' },
  { date: '10/03/2026', home: 'bier', away: 'jen', status: 'Sem. 12' },
  { date: '12/03/2026', home: 'marv', away: 'rhin', status: 'Sem. 12' },
  { date: '18/03/2026', home: 'rsc', away: 'manu', status: 'Reporté' },
  { date: '23/03/2026', home: 'rhin', away: 'rsc', status: 'Sem. 13' },
  { date: '23/03/2026', home: 'kiki', away: 'bier', status: 'Sem. 13' },
  { date: '25/03/2026', home: 'manu', away: 'resc', status: 'Sem. 13' },
  { date: '26/03/2026', home: 'marv', away: 'rhsp', status: 'Sem. 13' },
  { date: '26/03/2026', home: 'jen', away: 'star', status: 'Sem. 13' },
  { date: '30/03/2026', home: 'resc', away: 'marv', status: 'Sem. 14' },
  { date: '30/03/2026', home: 'star', away: 'manu', status: 'Sem. 14' },
  { date: '31/03/2026', home: 'bier', away: 'rhin', status: 'Sem. 14' },
  { date: '01/04/2026', home: 'rsc', away: 'rhsp', status: 'Sem. 14' },
  { date: '02/04/2026', home: 'jen', away: 'kiki', status: 'Sem. 14' },
  { date: '06/04/2026', home: 'rhsp', away: 'resc', status: 'Sem. 15' },
  { date: '06/04/2026', home: 'rhin', away: 'star', status: 'Sem. 15' },
  { date: '07/04/2026', home: 'bier', away: 'marv', status: 'Sem. 15' },
  { date: '08/04/2026', home: 'rsc', away: 'jen', status: 'Sem. 15' },
  { date: '08/04/2026', home: 'manu', away: 'kiki', status: 'Sem. 15' },
  { date: '04/05/2026', home: 'resc', away: 'kiki', status: 'Sem. 16' },
  { date: '04/05/2026', home: 'star', away: 'bier', status: 'Sem. 16' },
  { date: '04/05/2026', home: 'rhsp', away: 'rhin', status: 'Sem. 16' },
  { date: '06/05/2026', home: 'manu', away: 'rsc', status: 'Sem. 16' },
  { date: '07/05/2026', home: 'marv', away: 'jen', status: 'Sem. 16' },
  { date: '11/05/2026', home: 'resc', away: 'bier', status: 'Sem. 17' },
  { date: '11/05/2026', home: 'kiki', away: 'rhsp', status: 'Sem. 17' },
  { date: '13/05/2026', home: 'manu', away: 'marv', status: 'Sem. 17' },
  { date: '13/05/2026', home: 'rsc', away: 'star', status: 'Sem. 17' },
  { date: '14/05/2026', home: 'jen', away: 'rhin', status: 'Sem. 17' },
  { date: '18/05/2026', home: 'rhin', away: 'manu', status: 'Sem. 18' },
  { date: '18/05/2026', home: 'star', away: 'rhsp', status: 'Sem. 18' },
  { date: '19/05/2026', home: 'bier', away: 'rsc', status: 'Sem. 18' },
  { date: '21/05/2026', home: 'marv', away: 'kiki', status: 'Sem. 18' },
  { date: '21/05/2026', home: 'resc', away: 'jen', status: 'Sem. 18' },
  { date: '01/06/2026', home: 'resc', away: 'manu', status: 'Reporté' },
];

// 5. PR_TEAMS (Power Ranking - Equipes)
const PR_TEAMS = [
  { rank: 1, team: 'jen', record: '10-0', power: 100, calendar: '👑 Invaincu', diffClass: 'diff-easy' },
  { rank: 2, team: 'resc', record: '5-3', power: 76, calendar: '🔥 V vs Rhinos', diffClass: 'diff-easy' },
  { rank: 3, team: 'kiki', record: '7-2', power: 76, calendar: '🔥 V vs StarPAFF', diffClass: 'diff-easy' },
  { rank: 4, team: 'rhsp', record: '6-4', power: 65, calendar: '📉 D vs Jen', diffClass: 'diff-hard' },
  { rank: 5, team: 'marv', record: '6-4', power: 52, calendar: '📉 D vs RSC', diffClass: 'diff-hard' },
  { rank: 6, team: 'rhin', record: '2-7', power: 50, calendar: '📉 D vs Rescapés', diffClass: 'diff-hard' },
  { rank: 7, team: 'bier', record: '5-5', power: 49, calendar: '🔥 V vs Manu', diffClass: 'diff-easy' },
  { rank: 8, team: 'rsc', record: '3-5', power: 47, calendar: '🔥 V vs Marvels', diffClass: 'diff-easy' },
  { rank: 9, team: 'manu', record: '2-6', power: 33, calendar: '📉 D vs Bières', diffClass: 'diff-hard' },
  { rank: 10, team: 'star', record: '0-10', power: 0, calendar: '📉 10D consec.', diffClass: 'diff-hard' }
];

// 6. PR_PLAYERS (Power Ranking - Joueurs)
const PR_PLAYERS = [
  { rank: 1, name: 'Delmoly Alexandre ⭐⭐', team: 'jen', pos: 'Passeur', power: 100.0 },
  { rank: 2, name: 'Alves dupont Arnaud ⭐', team: 'jen', pos: 'R4', power: 98.5 },
  { rank: 3, name: 'Moroni Mikael', team: 'jen', pos: 'R4', power: 98.5 },
  { rank: 4, name: 'Melart Tom', team: 'jen', pos: 'Pointu', power: 98.2 },
  { rank: 5, name: 'Bouvier Lenny', team: 'jen', pos: 'Pointu', power: 98.2 },
  { rank: 6, name: 'Moroni Antoine', team: 'jen', pos: 'Pointu', power: 98.2 },
  { rank: 7, name: 'Gombert Jennifer', team: 'jen', pos: 'Centre', power: 97.9 },
  { rank: 8, name: 'Assumpcao Nicolas', team: 'jen', pos: 'Centre', power: 97.9 },
  { rank: 9, name: 'Le bihan Cyril', team: 'kiki', pos: 'Centre', power: 71.7 },
  { rank: 10, name: 'Simic Anthony', team: 'kiki', pos: 'Pointu', power: 71.5 },
  { rank: 11, name: 'Hure Robin ⭐', team: 'kiki', pos: 'Pointu', power: 71.5 },
  { rank: 12, name: 'Hibon Nicolas ⭐', team: 'kiki', pos: 'R4', power: 71.2 },
  { rank: 13, name: 'Popelut Romain', team: 'kiki', pos: 'R4', power: 71.2 },
  { rank: 14, name: 'Cotard Baptiste', team: 'kiki', pos: 'R4', power: 71.2 },
  { rank: 15, name: 'Pazmino Omar', team: 'kiki', pos: 'Passeur', power: 70.9 },
  { rank: 16, name: 'Leur Maxime ⭐⭐', team: 'kiki', pos: 'Passeur', power: 69.9 },
  { rank: 17, name: 'Martin Xavier', team: 'resc', pos: 'Centre', power: 69.7 },
  { rank: 18, name: 'Oliver Julien ⭐', team: 'rhsp', pos: 'Passeur', power: 69.4 },
  { rank: 19, name: 'Meridiano Yannick ⭐', team: 'rhsp', pos: 'R4', power: 69.0 },
  { rank: 20, name: 'Godeau Bastien', team: 'rhsp', pos: 'R4', power: 69.0 },
  { rank: 21, name: 'Bailly Jean-philippe ⭐', team: 'resc', pos: 'Pointu', power: 68.7 },
  { rank: 22, name: 'Evesque Mateusz ⭐', team: 'rhsp', pos: 'Pointu', power: 68.6 },
  { rank: 23, name: 'Goujon Adrien', team: 'rhsp', pos: 'Pointu', power: 68.6 },
  { rank: 24, name: 'Techer Kevin', team: 'rhsp', pos: 'Centre', power: 68.2 },
  { rank: 25, name: 'Vieira Matthieu', team: 'rhsp', pos: 'Centre', power: 68.2 },
  { rank: 26, name: 'Martins Celia', team: 'rhsp', pos: 'Centre', power: 68.2 },
  { rank: 27, name: 'Shue Yven ⭐', team: 'resc', pos: 'R4', power: 67.7 },
  { rank: 28, name: 'Michard Hugo', team: 'resc', pos: 'R4', power: 67.7 },
  { rank: 29, name: 'Michard Arthur ⭐⭐', team: 'resc', pos: 'Passeur', power: 62.8 },
  { rank: 30, name: 'Nedjar Yannick ⭐', team: 'marv', pos: 'Passeur', power: 59.3 },
  { rank: 31, name: 'Lavenet Jerome ⭐', team: 'marv', pos: 'R4', power: 58.0 },
  { rank: 32, name: 'Pauvert Thomas', team: 'marv', pos: 'R4', power: 58.0 },
  { rank: 33, name: 'Donjon Thibaud', team: 'marv', pos: 'R4', power: 58.0 },
  { rank: 34, name: 'Darrigol Hugo', team: 'marv', pos: 'Pointu', power: 56.8 },
  { rank: 35, name: 'Galland Matthieu ⭐', team: 'marv', pos: 'Centre', power: 55.6 },
  { rank: 36, name: 'Rocton Gaylord ⭐', team: 'rsc', pos: 'Passeur', power: 54.1 },
  { rank: 37, name: 'Redlich Olivier ⭐', team: 'rsc', pos: 'R4', power: 53.7 },
  { rank: 38, name: 'Teboul Jean pierre', team: 'rsc', pos: 'R4', power: 53.7 },
  { rank: 39, name: 'Kanounnikoff Francois', team: 'rsc', pos: 'Pointu', power: 53.3 },
  { rank: 40, name: 'Roux Philippe', team: 'rsc', pos: 'Pointu', power: 53.3 },
  { rank: 41, name: 'Courcelle Guillaume', team: 'rsc', pos: 'Centre', power: 52.9 },
  { rank: 42, name: 'Bisaro Marylin', team: 'rsc', pos: 'Centre', power: 52.9 },
  { rank: 43, name: 'Denis Natacha', team: 'rsc', pos: 'Centre', power: 52.9 },
  { rank: 44, name: 'Nicolas-flores Krystel', team: 'rsc', pos: 'Centre', power: 52.9 },
  { rank: 45, name: 'Garric Julien ⭐⭐⭐', team: 'bier', pos: 'Passeur', power: 48.9 },
  { rank: 46, name: 'Breleur Tony ⭐', team: 'bier', pos: 'R4', power: 48.8 },
  { rank: 47, name: 'Chaulet Didier ⭐', team: 'bier', pos: 'Pointu', power: 48.8 },
  { rank: 48, name: 'Bone Ida', team: 'bier', pos: 'Centre', power: 48.8 },
  { rank: 49, name: 'Neyraud Gawen ⭐', team: 'bier', pos: 'Centre', power: 48.8 },
  { rank: 50, name: 'Noyelle Nolwen', team: 'bier', pos: 'Centre', power: 48.8 },
  { rank: 51, name: 'Patrocinio Neli', team: 'bier', pos: 'Centre', power: 48.8 },
  { rank: 52, name: 'Buyse Henri ⭐', team: 'rhin', pos: 'Centre', power: 42.4 },
  { rank: 53, name: 'Pelleray Mathieu', team: 'rhin', pos: 'Centre', power: 42.4 },
  { rank: 54, name: 'Leca Arthur', team: 'rhin', pos: 'Pointu', power: 41.3 },
  { rank: 55, name: 'Blanquer Antoine', team: 'rhin', pos: 'R4', power: 40.1 },
  { rank: 56, name: 'Wairy Jean ⭐', team: 'rhin', pos: 'Passeur', power: 39.0 },
  { rank: 57, name: 'Amesee Stephane ⭐', team: 'manu', pos: 'Passeur', power: 36.9 },
  { rank: 58, name: 'Vernazobres Lionel', team: 'manu', pos: 'R4', power: 36.7 },
  { rank: 59, name: 'Poncharville Prosper', team: 'manu', pos: 'Pointu', power: 36.4 },
  { rank: 60, name: 'De gonfreville Emmanuelle', team: 'manu', pos: 'Centre', power: 36.1 },
  { rank: 61, name: 'Roussiere Andy', team: 'manu', pos: 'Centre', power: 36.1 },
  { rank: 62, name: 'Rabiarivelo Ilo', team: 'star', pos: 'Centre', power: 0.6 },
  { rank: 63, name: 'Mehallel Hamsa', team: 'star', pos: 'Centre', power: 0.6 },
  { rank: 64, name: 'Bakouri Mehdi', team: 'star', pos: 'Centre', power: 0.6 },
  { rank: 65, name: 'Nieto Victor', team: 'star', pos: 'Pointu', power: 0.4 },
  { rank: 66, name: 'Ha Bryan', team: 'star', pos: 'Pointu', power: 0.4 },
  { rank: 67, name: 'Ty Samneang', team: 'star', pos: 'R4', power: 0.2 },
  { rank: 68, name: 'Bento dos santos Lucas', team: 'star', pos: 'R4', power: 0.2 },
  { rank: 69, name: 'Vulgaire Thierry', team: 'star', pos: 'R4', power: 0.2 },
  { rank: 70, name: 'Julien François', team: 'star', pos: 'R4', power: 0.2 },
  { rank: 71, name: 'Vincent dit mahaut Julien ⭐', team: 'star', pos: 'Passeur', power: 0.0 }
];


// 7. EVOLUTION_DATA
const EVOLUTION_DATA = {
  teams: {
    'Jen': { color: '#9b59b6', points: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20], rank: 1 },
    'Kiki': { color: '#3498db', points: [0, 2, 4, 5, 7, 9, 11, 13, 14, 16], rank: 2 },
    'Red Hot': { color: '#e74c3c', points: [0, 1, 3, 5, 7, 9, 11, 12, 14, 15, 16], rank: 4 },
    'Rescapés': { color: '#2ecc71', points: [0, 2, 4, 6, 7, 8, 10, 11, 13], rank: 3 },
    'Marvels': { color: '#f39c12', points: [0, 2, 4, 5, 7, 9, 10, 12, 13, 15, 16], rank: 5 },
    'RSC': { color: '#1abc9c', points: [0, 1, 3, 4, 5, 7, 8, 9, 11], rank: 7 },
    'Manu': { color: '#e67e22', points: [0, 1, 2, 4, 5, 6, 8, 9, 10], rank: 8 },
    'Bières': { color: '#f1c40f', points: [0, 2, 3, 4, 5, 7, 8, 9, 11, 13, 15], rank: 6 },
    'Rhinos': { color: '#95a5a6', points: [0, 1, 2, 3, 4, 6, 7, 8, 10, 11], rank: 9 },
    'StarPAFF': { color: '#34495e', points: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], rank: 10 }
  }
};
